import Head from "next/head";
import { useState } from "react";
import MyButton from "./my-button";

const max_counter = 10;
const min_counter = -10;

export default function Home() {
  const [ count, setCount ] = useState(0);
  const [ tempCount, setTempCount ] = useState(null);
  
  const increaseCounter = () => {
    if (count >= max_counter) {
      alert("max counter reached");
      return;
    }
    setCount(count + 1);
  }

  const decreaseCounter = () => {
    if (count <= min_counter) {
      alert("min counter reached");
      return;
    }
    setCount(count - 1)
  }

  const handleInput = (e) => {
    const value = e.target.value;
    setTempCount(Number(value));
  }

  const handleReset = () => {
    setCount(tempCount);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="heading">Hello {count}</h1>
        <MyButton
          text="decrease counter"
          onClick={decreaseCounter}
        />
        <MyButton 
          text="increase counter" 
          onClick={increaseCounter}
        />
        <input
          onInput={handleInput}
        />
        <MyButton
          text="reset to custom value"
          onClick={handleReset}
        />
      </main>
    </>
  );
}
